name:                rest-easy
version:             0.1.0.0
github:              "githubuser/rest-easy"
license:             BSD3
author:              "Dustin Segers"
maintainer:          "dustin.segers@gmail.com"
copyright:           "2021 Dustin Segers"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rest-easy#readme>

default-extensions:
- OverloadedStrings
- DeriveGeneric

dependencies:
- base >= 4.7 && < 5
- aeson
- scotty
- time
- text

library:
  source-dirs: src

executables:
  rest-easy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rest-easy

tests:
  rest-easy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rest-easy
